### PR TITLE
Post-workshop fixes

### PR DESCRIPTION
**Pull request by rhagenson**
Every error/major issue with lesson content we ran into during teaching should be fixed at this point. Most importantly I added instructions on starting the large file transfer that majorly delayed us to the first day by using nohup.

### CODE REVIEW

**Review by CarrieBrown — CHANGES_REQUESTED** [review]
Would it be possible to change the timing of this command instead of introducing nohup. We generally tend to discourage the use of nohup on the clusters and with novice users this can be a dangerous tool.

**Comment by acaprez** [comment]
Yeah, we generally consider `nohup` to be bad practice.

**Comment by rhagenson** [comment]
Absolutely. I can submit changes tomorrow. I do not believe we can push this transfer any further forward in the lesson as it currently is just after creating the `dc_workshop` directory structure on Day 1 as well as is used early in the first lesson on Day 2. The best alternatives I can think of right now are:

1. Open a second connection to HCC Day 1 at this same point to remove need for nuhup and have instructors/helpers aid those whose transfer does not finish by the end of the lesson, or
2. Start the transfer immediately Day 2 and fill time with a review of Day 1 and general outline of the Day 2 topics

Is either of this preferred or is there a third option that you had in mind?

**Comment by CarrieBrown** [comment]
I think either of those options would work well. For day 1, doing it immediately after making the directories would allow time for the transfer to continue while creating the log file and doing the sticky note survey. Doing on Day 2 would also work as long as you do it immediately in the morning. The discussion over the FASTQ format has the attendees looking at the same file they transferred over in their initial directories so it could use that one during that discussion, giving time for the transfer to complete. Another option would be to have the users download a zip of all of the files themselves and move them as needed (I believe this would speed things up because they wouldn’t all be trying to read from the same files and moving files is quicker than copying them). But this would require more in depth lesson changes.

I’m ok with any of these options. Given the time crunch on day two, perhaps putt it in at the end of Day 1 would be the best idea.

**Comment by rhagenson** [comment]
@CarrieBrown Updated to remove use of `nohup`. 

Since the transfer is not running in the background now I also added a brief section to Day 1 seeking help if the transfer is not done and double-check on Day 2 for what the directory should look like.

**Pull request merged**
